name: Docker Image CI

on:
  push:
    branches: [ arm64 ]
  pull_request:
    branches: [ arm64 ]

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      DOCKER_PLATFORMS: linux/amd64,linux/armhf,linux/arm64


    steps:
    -
        name: Checkout
        uses: actions/checkout@v3
    -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
    -
        name: setup docker buildx
        uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true
    -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
    - 
      name: Build the Docker image
      run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes && docker buildx install && docker buildx create --name multiarch --driver docker-container --use && docker buildx create --name arm --platform linux/amd64,linux/armhf,linux/arm64 --driver docker-container --use && docker buildx inspect arm64 --bootstrap && docker buildx use arm64 && docker run --rm --privileged multiarch/qemu-user-static:register --reset && docker buildx build --platform linux/amd64,linux/armhf,linux/arm64 -t simeononsecurity/helium_diy_middleman:latest-arm64 --progress=plain --push .
    -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: simeononsecurity/helium_diy_middleman:latest-arm64

          