name: Docker Image CI

on:
  push:
    branches: [ arm64 ]
  pull_request:
    branches: [ arm64 ]

jobs:

  build:

    runs-on: multiarch/ubuntu-core
    env:
      DOCKER_PLATFORMS: linux/amd64,linux/arm64


    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker buildx install && docker buildx create --name mybuilder && docker buildx use mybuilder && docker run --rm --privileged multiarch/qemu-user-static:register --reset && docker buildx build --platform linux/amd64,linux/arm64 -t simeononsecurity/helium_diy_middleman:latest-arm64 --progress=plain --push .
    -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
    -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: simeononsecurity/helium_diy_middleman:latest-arm64
